baseURL = 'https://boozer.asia/'
languageCode = 'en-us'
title = '亚洲豪饮者'
theme = 'paper'

[params]
  # homepage profile
  avatar = 'https://gravatar.com/avatar/8fa10b04600be9bab86ec8a8fa60dd78bab9434f14264629f0b82b98f6755d13.jpg'
  name = 'Cory'
  bio = 'A man who loves to drink and write code.'

  # homepage social
  github = 'ManicEuphoria'
  unsplash = 'euphoray'
  rss = true
